#!/usr/bin/env node
// ============================================================
// ASTERION ONE — canonicalJSON Standalone Tests
// ============================================================
// Verifies that canonicalJSON() produces output identical to
// Python's json.dumps(obj, sort_keys=True, separators=(',',':'))
//
// This test has ZERO dependencies — runs with just Node.js.
// It extracts the pure canonicalJSON/sortDeep functions and
// tests them against known Python outputs.
//
// Run: node ground/ui/src/lib/__tests__/canonical_json.test.mjs
//
// Ref: SD-1C, ICD §2.3 IF-WS-002 — CANONICAL JSON FOR SIGNING
// Req: REQ-SEC-ED25519 (cross-platform hash compatibility)
// ============================================================

// ── Extract pure functions (no imports needed) ───────────

function sortDeep(value) {
  if (value === null || value === undefined) return value;
  if (Array.isArray(value)) return value.map(sortDeep);
  if (typeof value === 'object') {
    const sorted = {};
    for (const key of Object.keys(value).sort()) {
      sorted[key] = sortDeep(value[key]);
    }
    return sorted;
  }
  return value;
}

function canonicalJSON(obj) {
  return JSON.stringify(sortDeep(obj));
}

// ── Test Harness ─────────────────────────────────────────

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.log(`  ✗ ${name}`);
    console.log(`    ${err.message}`);
    failed++;
  }
}

function expect(actual) {
  return {
    toBe(expected) {
      if (actual !== expected) {
        throw new Error(`Expected: ${JSON.stringify(expected)}\n    Actual:   ${JSON.stringify(actual)}`);
      }
    },
    toEqual(expected) {
      const a = JSON.stringify(actual);
      const b = JSON.stringify(expected);
      if (a !== b) {
        throw new Error(`Expected: ${b}\n    Actual:   ${a}`);
      }
    },
  };
}

// ── Tests ────────────────────────────────────────────────

console.log('\n=== canonicalJSON Tests (REQ-SEC-ED25519 cross-compatibility) ===\n');

// ── 1. Basic key sorting ──

test('sorts top-level keys alphabetically', () => {
  const input = { zebra: 1, alpha: 2, mid: 3 };
  expect(canonicalJSON(input)).toBe('{"alpha":2,"mid":3,"zebra":1}');
});

test('empty object', () => {
  expect(canonicalJSON({})).toBe('{}');
});

test('empty array', () => {
  expect(canonicalJSON([])).toBe('[]');
});

test('null value', () => {
  expect(canonicalJSON(null)).toBe('null');
});

test('string value', () => {
  expect(canonicalJSON('hello')).toBe('"hello"');
});

test('number value', () => {
  expect(canonicalJSON(42)).toBe('42');
});

// ── 2. Nested key sorting ──

test('sorts nested object keys recursively', () => {
  const input = { z: { b: 1, a: 2 }, a: { d: 3, c: 4 } };
  expect(canonicalJSON(input)).toBe('{"a":{"c":4,"d":3},"z":{"a":2,"b":1}}');
});

test('sorts keys inside array elements', () => {
  const input = [{ z: 1, a: 2 }, { m: 3, b: 4 }];
  expect(canonicalJSON(input)).toBe('[{"a":2,"z":1},{"b":4,"m":3}]');
});

test('preserves array element ORDER (only sorts keys within elements)', () => {
  const input = [3, 1, 2];
  expect(canonicalJSON(input)).toBe('[3,1,2]');
});

// ── 3. ICD IF-WS-002 command structure ──

test('canonical command structure per ICD IF-WS-002', () => {
  const commands = [
    {
      sequence_id: 1,
      command_type: 'SET_PARAM',
      payload: { param_value: 2, param_name: 'telem_freq' },
    },
    {
      sequence_id: 2,
      command_type: 'RUN_DIAGNOSTIC',
      payload: { subsystem: 'thermal' },
    },
  ];

  const result = canonicalJSON(commands);

  // Python equivalent: json.dumps(commands, sort_keys=True, separators=(',',':'))
  // Expected: keys sorted at every level
  const expected =
    '[{"command_type":"SET_PARAM","payload":{"param_name":"telem_freq","param_value":2},"sequence_id":1},' +
    '{"command_type":"RUN_DIAGNOSTIC","payload":{"subsystem":"thermal"},"sequence_id":2}]';

  expect(result).toBe(expected);
});

// ── 4. Python compatibility (pre-computed reference values) ──
// These expected values were generated by:
//   python3 -c "import json; print(json.dumps(OBJ, sort_keys=True, separators=(',',':')))"

test('matches Python output: simple object', () => {
  // python3 -c "import json; print(json.dumps({'b': 2, 'a': 1}, sort_keys=True, separators=(',',':')))"
  // Output: {"a":1,"b":2}
  expect(canonicalJSON({ b: 2, a: 1 })).toBe('{"a":1,"b":2}');
});

test('matches Python output: nested with arrays', () => {
  // python3 -c "import json; print(json.dumps({'z': [{'c': 3, 'a': 1}], 'a': 'hello'}, sort_keys=True, separators=(',',':')))"
  // Output: {"a":"hello","z":[{"a":1,"c":3}]}
  expect(canonicalJSON({ z: [{ c: 3, a: 1 }], a: 'hello' })).toBe(
    '{"a":"hello","z":[{"a":1,"c":3}]}'
  );
});

test('matches Python output: boolean and null values', () => {
  // python3 -c "import json; print(json.dumps({'c': None, 'b': True, 'a': False}, sort_keys=True, separators=(',',':')))"
  // Output: {"a":false,"b":true,"c":null}
  expect(canonicalJSON({ c: null, b: true, a: false })).toBe(
    '{"a":false,"b":true,"c":null}'
  );
});

test('matches Python output: realistic command plan payload', () => {
  // The exact structure that will be signed by both browser and verified by Flight
  const commands = [
    {
      sequence_id: 1,
      command_type: 'SET_PARAM',
      payload: { param_name: 'gain', param_value: 3.5 },
    },
    {
      sequence_id: 2,
      command_type: 'SET_MODE',
      payload: { target_mode: 'NOMINAL' },
    },
    {
      sequence_id: 3,
      command_type: 'RUN_DIAGNOSTIC',
      payload: { subsystem: 'THERMAL', verbose: true },
    },
  ];

  const result = canonicalJSON(commands);

  // python3 -c "
  // import json
  // cmds = [
  //   {'sequence_id': 1, 'command_type': 'SET_PARAM', 'payload': {'param_name': 'gain', 'param_value': 3.5}},
  //   {'sequence_id': 2, 'command_type': 'SET_MODE', 'payload': {'target_mode': 'NOMINAL'}},
  //   {'sequence_id': 3, 'command_type': 'RUN_DIAGNOSTIC', 'payload': {'subsystem': 'THERMAL', 'verbose': True}},
  // ]
  // print(json.dumps(cmds, sort_keys=True, separators=(',',':')))
  // "
  const expected =
    '[{"command_type":"SET_PARAM","payload":{"param_name":"gain","param_value":3.5},"sequence_id":1},' +
    '{"command_type":"SET_MODE","payload":{"target_mode":"NOMINAL"},"sequence_id":2},' +
    '{"command_type":"RUN_DIAGNOSTIC","payload":{"subsystem":"THERMAL","verbose":true},"sequence_id":3}]';

  expect(result).toBe(expected);
});

// ── 5. Edge cases ──

test('handles deeply nested objects (3 levels)', () => {
  const input = { c: { b: { a: 1, z: 2 }, a: 3 }, a: 4 };
  expect(canonicalJSON(input)).toBe('{"a":4,"c":{"a":3,"b":{"a":1,"z":2}}}');
});

test('handles mixed arrays and objects', () => {
  const input = { data: [1, 'two', { z: 3, a: 4 }, [5, 6]] };
  expect(canonicalJSON(input)).toBe('{"data":[1,"two",{"a":4,"z":3},[5,6]]}');
});

test('handles special characters in strings', () => {
  const input = { desc: 'NOMINAL → SAFE: 78.2°C > 75.0°C' };
  expect(canonicalJSON(input)).toBe('{"desc":"NOMINAL → SAFE: 78.2°C > 75.0°C"}');
});

// ── Summary ──────────────────────────────────────────────

console.log(`\n  Results: ${passed} passed, ${failed} failed, ${passed + failed} total`);

if (failed > 0) {
  console.log('\n  ✗ FAIL — canonicalJSON does NOT match Python output');
  process.exit(1);
} else {
  console.log('\n  ✓ PASS — canonicalJSON matches Python json.dumps(sort_keys=True, separators=(\',\',\':\'))');
  console.log('  ✓ Cross-platform signing compatibility confirmed [REQ-SEC-ED25519]\n');
  process.exit(0);
}
